packages:
  - apps/*
  - scripts/*
  - packages/*
  - packages/@core/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - internal/*
  - internal/lint-configs/*
catalog:
  "@changesets/changelog-github": ^0.5.0
  "@changesets/cli": ^2.27.11
  "@changesets/git": 3.0.2
  "@commitlint/cli": 19.5.0
  "@commitlint/config-conventional": 19.5.0
  "@ctrl/tinycolor": 4.1.0
  "@eslint/js": 9.14.0
  "@iconify/json": ^2.2.290
  "@iconify/tailwind": ^1.2.0
  "@iconify/vue": 4.3.0
  "@intlify/unplugin-vue-i18n": 6.0.2
  "@manypkg/get-packages": ^2.2.2
  "@pnpm/workspace.read-manifest": 1000.0.1
  "@stylistic/stylelint-plugin": 3.1.1
  "@tailwindcss/nesting": 0.0.0-insiders.565cd3e
  "@tailwindcss/typography": ^0.5.15
  "@tanstack/vue-store": 0.7.0
  "@types/archiver": 6.0.3
  "@types/html-minifier-terser": 7.0.2
  "@types/lodash.clonedeep": 4.5.9
  "@types/lodash.get": 4.4.9
  "@types/lodash.isequal": 4.5.8
  "@types/node": ^22.10.5
  "@types/nprogress": 0.2.3
  "@types/postcss-import": ^14.0.3
  "@types/sortablejs": 1.15.8
  "@vee-validate/zod": ^4.15.0
  "@vitejs/plugin-vue": ^5.2.1
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "@vue/shared": 3.5.13
  "@vueuse/core": 12.3.0
  archiver: 7.0.1
  autoprefixer: ^10.4.20
  boxen: 8.0.1
  chalk: 5.3.0
  cheerio: 1.0.0
  class-variance-authority: ^0.7.1
  clsx: 2.1.1
  commitlint-plugin-function-rules: 4.0.1
  consola: 3.2.3
  cross-env: ^7.0.3
  cspell: ^8.17.1
  cssnano: ^7.0.6
  cz-git: 1.11.0
  czg: 1.11.0
  dayjs: 1.11.13
  defu: 6.1.4
  dotenv: 16.4.7
  eslint: 9.14.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-prettier: 5.2.1
  eslint-plugin-unused-imports: 4.1.4
  eslint-plugin-vue: 9.30.0
  execa: 9.5.1
  filesize: 10.1.6
  find-up: 7.0.0
  get-port: 7.1.0
  globals: 15.12.0
  gradient-string: 3.0.0
  html-minifier-terser: 7.2.0
  husky: 9.1.7
  lint-staged: ^15.3.0
  lodash.clonedeep: 4.5.0
  lodash.get: 4.4.2
  lodash.isequal: 4.5.0
  lucide-vue-next: ^0.469.0
  nitropack: 2.10.4
  nprogress: 0.2.0
  ora: 8.1.1
  pkg-types: 1.2.1
  postcss: ^8.4.49
  postcss-antd-fixes: ^0.2.0
  postcss-html: 1.7.0
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.3
  postcss-scss: 4.0.9
  prettier: 3.3.3
  radix-vue: ^1.9.12
  resolve.exports: 2.0.3
  rimraf: ^6.0.1
  rollup: 4.28.1
  rollup-plugin-visualizer: 5.12.0
  sass: 1.82.0
  sortablejs: 1.15.6
  stylelint: 16.10.0
  stylelint-config-recess-order: 5.1.1
  stylelint-config-recommended: 14.0.1
  stylelint-config-recommended-scss: 14.1.0
  stylelint-config-recommended-vue: 1.5.0
  stylelint-config-standard: 36.0.1
  stylelint-order: 6.0.4
  stylelint-prettier: 5.0.2
  stylelint-scss: 6.9.0
  tailwind-merge: 2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  theme-colors: 0.1.0
  turbo: 2.3.3
  typescript: ^5.7.2
  typescript-eslint: 8.13.0
  unbuild: ^3.2.0
  vee-validate: ^4.15.0
  vite: ^6.0.5
  vite-plugin-compression: 0.5.1
  vite-plugin-dts: 4.3.0
  vite-plugin-html: 3.2.2
  vite-plugin-lazy-import: 1.0.7
  vite-plugin-pwa: 0.21.1
  vite-plugin-vue-devtools: 7.6.8
  vitest: ^2.1.8
  vue: 3.5.13
  vue-eslint-parser: 9.4.3
  vue-router: 4.5.0
  vue-tsc: ^2.2.0
  zod: ^3.24.1
  zod-defaults: ^0.1.3
